# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: localPool

variables:
  SONARQUBE_PROJECT_KEY: 'Art_Marketplace_Art_Marketplace_c6b13971-365e-45d9-98e2-18005c410f18'  # Replace with your SonarQube project key
  SONARQUBE_SERVICE_CONNECTION: 'My_SonarQube'  # Replace with your SonarQube service connection name


steps:

# Step 2: Prepare SonarQube analysis
- task: SonarQubePrepare@5
  inputs:
    SonarQube: '$(SONARQUBE_SERVICE_CONNECTION)'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '$(SONARQUBE_PROJECT_KEY)'
    cliSources: '.'  # Root folder of your project
    extraProperties: |
      sonar.exclusions=**/node_modules/**,**/*.spec.ts  # Exclude specific folders/files
      sonar.typescript.lcov.reportPaths=coverage/lcov.info  # Set code coverage report path (if applicable)


# Step 3: Install dependencies and build Angular project
- script: |
    cd ArtMarket
    ng build --prod
    npm pack
  displayName: 'npm build and package'

  # Step 4: Run SonarQube analysis
- task: SonarQubeAnalyze@5
  displayName: 'Run SonarQube analysis'

# Step 5: Publish SonarQube quality gate results
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish SonarQube quality gate results'

- task: npmAuthenticate@0
  inputs:
    workingFile: ./ArtMarket/.npmrc


- task: Npm@1
  inputs:
    command: 'publish'
    publishRegistry: 'useFeed'
    publishFeed: '22abed3e-a7dd-43a5-9b98-52ef5521bbcb/3d91f424-c466-461c-80b0-9a360d82c0cf'
  displayName: 'Publish package to Azure Artifacts'

