# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: localPool

variables:
  SONARQUBE_PROJECT_KEY: 'Art_Marketplace_Art_Marketplace_c6b13971-365e-45d9-98e2-18005c410f18'  # Replace with your SonarQube project key
  SONARQUBE_SERVICE_CONNECTION: 'My_SonarQube'  # Replace with your SonarQube service connection name
  FEED_NAME: 'my-artifact-feed'  # Replace with your Azure Artifacts feed name
  PACKAGE_NAME: 'art-market'  # Replace with your package name
  NODE_ENV: 'production'
  PACKAGE_VERSION: '$(Build.BuildId)'  # Semantic version using the build ID
  DOCKER_REGISTRY: 'docker.io'  # Docker Hub registry
  DOCKER_USERNAME: $(DOCKER_USERNAME)  # Reference secret variable for username
  DOCKER_PASSWORD: $(DOCKER_PASSWORD)  # Reference secret variable for password or token
  IMAGE_TAG: '$(Build.BuildId)'


steps:
# Step 1: Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'


# Step 2: Prepare SonarQube analysis
- task: SonarQubePrepare@5
  inputs:
    SonarQube: '$(SONARQUBE_SERVICE_CONNECTION)'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '$(SONARQUBE_PROJECT_KEY)'
    cliSources: '.'  # Root folder of your project
    extraProperties: |
      sonar.exclusions=**/node_modules/**,**/*.spec.ts  # Exclude specific folders/files
      sonar.typescript.lcov.reportPaths=coverage/lcov.info  # Set code coverage report path (if applicable)


# Step 3: Install dependencies and build Angular project
- script: |
    npm install -g @angular/cli
    cd ArtMarket
    npm install
    ng build --prod
  displayName: 'npm install and build'

  # Step 4: Run SonarQube analysis
- task: SonarQubeAnalyze@5
  displayName: 'Run SonarQube analysis'

# Step 5: Publish SonarQube quality gate results
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish SonarQube quality gate results'

- script: |
    cd ArtMarket
    npm version --no-git-tag-version 1.0.$(Build.BuildId)
    npm pack
  displayName: 'Package project'

  # Step 2: Verify package creation
- script: |
    cd ArtMarket
    dir
  displayName: 'Verify package creation'

  
- script: |
    echo DOCKER_USERNAME=$(DOCKER_USERNAME)
    echo IMAGE_TAG=$(IMAGE_TAG)
  displayName: 'Debug Variables'

  # Step 1: Login to Docker Hub
- task: Docker@2
  inputs:
    command: 'login'
    containerRegistry: '$(DOCKER_REGISTRY)'
    username: '$(DOCKER_USERNAME)'  # Use the secret variable
    password: '$(DOCKER_PASSWORD)'  # Use the secret variable
  displayName: 'Login to Docker Hub'

- script: |
    echo DOCKER_USERNAME=$(DOCKER_USERNAME)
    echo IMAGE_TAG=$(IMAGE_TAG)
  displayName: 'Debug Variables'

# Step 2: Build Docker Image
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: './myimg.Dockerfile'
    tags: '$(DOCKER_USERNAME)/myImage:$(IMAGE_TAG)'
  displayName: 'Build Docker Image'

- script: |
    npm install -g snyk
  displayName: 'Install Snyk'

# Authenticate Snyk (Replace with your Snyk API Token)
- script: |
    snyk auth 8be4abeb-83d5-4e17-acb6-85ef62f8c7d8
  displayName: 'Authenticate Snyk'

# Scan Docker Image using Snyk
- script: |
    snyk container test $(DOCKER_USERNAME)/myImage:$(IMAGE_TAG)
  displayName: 'Scan Docker Image with Snyk'

# Step 3: Push Docker Image to Docker Hub
- task: Docker@2
  inputs:
    command: 'push'
    tags: '$(DOCKER_USERNAME)/myImage:$(IMAGE_TAG)'
  displayName: 'Push Docker Image to Docker Hub'


# Step 7: Push package to Azure Artifacts
- task: npm@1
  inputs:
    command: 'custom'
    customCommand: 'publish ./ArtMarket/art-market-1.0.$(Build.BuildId).tgz --registry https://pkgs.dev.azure.com/$(System.CollectionId)/_packaging/$(FEED_NAME)/npm/registry/'
    verbose: true
  displayName: 'Push package to Azure Artifacts'
