# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: localPool

variables:
  SONARQUBE_PROJECT_KEY: 'Art_Marketplace_Art_Marketplace_c6b13971-365e-45d9-98e2-18005c410f18'  # Replace with your SonarQube project key
  SONARQUBE_SERVICE_CONNECTION: 'My_SonarQube'  # Replace with your SonarQube service connection name
  FEED_NAME: 'my-artifact-feed'  # Replace with your Azure Artifacts feed name
  PACKAGE_NAME: 'art-market'  # Replace with your package name
  NODE_ENV: 'production'
  PACKAGE_VERSION: '$(Build.BuildId)'  # Semantic version using the build ID


steps:
# Step 1: Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'



# Step 2: Prepare SonarQube analysis
- task: SonarQubePrepare@5
  inputs:
    SonarQube: '$(SONARQUBE_SERVICE_CONNECTION)'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '$(SONARQUBE_PROJECT_KEY)'
    cliSources: '.'  # Root folder of your project
    extraProperties: |
      sonar.exclusions=**/node_modules/**,**/*.spec.ts  # Exclude specific folders/files
      sonar.typescript.lcov.reportPaths=coverage/lcov.info  # Set code coverage report path (if applicable)


# Step 3: Install dependencies and build Angular project
- script: |
    npm install -g @angular/cli
    cd ArtMarket
    npm install
    ng build --prod
    npm test -- --watch=false --code-coverage
  displayName: 'npm install and build and testing'

# Step 5: Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'ArtMarket/coverage/**/test-results.xml'
    testRunTitle: 'Unit Tests'
  displayName: 'Publish test results'

  # Step 4: Run SonarQube analysis
- task: SonarQubeAnalyze@5
  displayName: 'Run SonarQube analysis'

# Step 5: Publish SonarQube quality gate results
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish SonarQube quality gate results'

- script: |
    cd ArtMarket
    npm version --no-git-tag-version 1.0.$(Build.BuildId)
    npm pack
  displayName: 'Package project'

  # Step 2: Verify package creation
- script: |
    cd ArtMarket
    dir
  displayName: 'Verify package creation'


#step 1: login to docker hub
- task: Docker@2
  inputs:
    containerRegistry: 'docker.io'
    command: 'login'
  displayName: 'Login to Docker Hub'


- task: Docker@2
  inputs:
    containerRegistry: 'docker.io'
    repository: 'ibtihel2001/nodeproject'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
  displayName: 'Build and push Docker image'

# Step 3: Security Scan Docker Image
- task: Docker@2
  inputs:
    containerRegistry: 'docker.io'
    repository: 'ibtihel2001/nodeproject'
    command: 'run'
    arguments: 'docker scan ibtihel2001/nodeproject:latest --file **/Dockerfile'
  displayName: 'Scan Docker Image for Vulnerabilities'
# Step 3: Push Docker Image to Docker Hub



# Authenticate Snyk (Replace with your Snyk API Token)
- script: |
    snyk auth 8be4abeb-83d5-4e17-acb6-85ef62f8c7d8
  displayName: 'Authenticate Snyk'



# Step 7: Push package to Azure Artifacts
- task: npmAuthenticate@0
  inputs:
    workingFile: ./ArtMarket/.npmrc
  displayName: 'Authenticate to Azure Artifacts'


- task: Npm@1
  inputs:
    workingDir: './ArtMarket'
    command: 'publish'
    publishRegistry: 'useFeed'
    publishFeed: '22abed3e-a7dd-43a5-9b98-52ef5521bbcb/3d91f424-c466-461c-80b0-9a360d82c0cf'
  displayName: 'Push package to Azure Artifacts'
